import {StyleSheet} from 'react-native';
import DP from 'Root/config/dp';

export const organism_style = StyleSheet.create({
	feedContent: {
		flexDirection: 'column',
		width: 750 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EDE8A6',
	},
	userLocationLabel_view_feedContent: {
		flexDirection: 'row',
		width: 654 * DP,
		marginTop: 78 * DP,
	},
	userLocationLabel_feedContent: {
		flexDirection: 'row',
		width: 448 * DP,
		backgroundColor: '#0FA743',
	},
	feed: {
		flexDirection: 'column',
		width: 750 * DP,
		height: 1222 * DP,
		alignItems: 'center',
		justifyContent: 'center',
	},
	feedMedia: {
		width: 750 * DP,
		height: 1222 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	likeCommentButtons: {
		width: 750 * DP,
		height: 1222 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	likeCommentInfo: {
		width: 750 * DP,
		height: 1222 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	recentComment: {
		width: 750 * DP,
		height: 1222 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	meatball: {
		width: 50 * DP,
		height: 50 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#CAD0F2',
	},
	content_feedContent: {
		width: 654 * DP,
		height: 86 * DP,
		justifyContent: 'center',
		backgroundColor: '#0FA743',
	},
	time_view_feedContent: {
		flexDirection: 'row',
		width: 654 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'space-between',
		backgroundColor: '#C1EDD0',
	},
	time_feedContent: {
		flexDirection: 'row',
		width: 110 * DP,
		height: 36 * DP,
		justifyContent: 'center',
		backgroundColor: '#F2CACA',
	},
	addMore_view_feedContent: {
		flexDirection: 'row',
		width: 108 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
	},
	addMore_feedContent: {
		width: 60 * DP,
		height: 36 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F2CACA',
	},
	braket: {
		width: 48 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#CAD0F2',
	},
	tipOff_feedContent: {
		width: 654 * DP,
		justifyContent: 'center',
		backgroundColor: '#0FA743',
	},
	button_view_feedContent: {
		flexDirection: 'row',
		width: 126 * DP,
		alignItems: 'center',
		justifyContent: 'space-between',
		backgroundColor: '#C1EDD0',
	},
	favoriteTag_view_feedContent: {
		flexDirection: 'column',
		width: 48 * DP,
		height: 84 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4B6EE1',
	},
	favoriteTag_feedContent: {
		width: 48 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#AEB7EF',
	},
	like_count_feedContent: {
		width: 44 * DP,
		height: 35 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EED3D3',
	},
	share48_view_feedContent: {
		width: 48 * DP,
		height: 84 * DP,
		alignItems: 'center',
		justifyContent: 'center',
	},
	share48_feedContent: {
		width: 48 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#AEB7EF',
	},
	share_feedContent: {
		width: 44 * DP,
		height: 35 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4B6EE1',
	},
	feedMedia_feed: {
		width: 750 * DP,
		height: 750 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#0FA743',
	},
	comment_feed_view: {
		width: 750 * DP,
		height: 202 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EBC48E',
	},
	likeCommentButtons_view: {
		width: 654 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#BAA568',
	},
	likeCommentButtons: {
		width: 654 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#BAA568',
	},
	recentComment_view: {
		width: 654 * DP,
		height: 76 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	likeCommentInfo_view: {
		width: 256 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4AAA60',
	},
	like48: {
		width: 48 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F8DDDD',
	},
	like_count_view_feed: {
		width: 92 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4AAA60',
	},
	like_count_feed: {
		width: 92 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4AAA60',
	},
	comment48: {
		width: 48 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F8DDDD',
	},
	comment_count_view_feed: {
		width: 68 * DP,
		height: 48 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#4AAA60',
	},
	comment_count_feed: {
		width: 56 * DP,
		height: 30 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F8DDDD',
	},
	writerID_feed_view: {
		width: 116 * DP,
		height: 76 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#C1DAF6',
	},
	writerID_feed: {
		width: 96 * DP,
		height: 36 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#AAE8B6',
	},
	commentText_view: {
		width: 538 * DP,
		height: 76 * DP,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#AAE8B6',
	},
});

export const feedContent_style = StyleSheet.create({
	status: {
		marginLeft: 14 * DP,
	},
	meatball: {
		marginLeft: 12 * DP,
	},
	content: {
		marginTop: 20 * DP,
	},
	tipOff: {
		marginTop: 16 * DP,
	},
	like_count: {
		marginTop: 1 * DP,
	},
	share: {
		marginTop: 1 * DP,
	},
});

export const feed_style = StyleSheet.create({
	like_count: {
		marginLeft: 12 * DP,
		marginTop: 9 * DP,
	},
	recentComment: {
		marginLeft: 24 * DP,
		marginTop: 24 * DP,
	},
	likeCommentButtons: {
		marginTop: 24 * DP,
	},
});
